from dataclasses import dataclass
from typing import Protocol
from core.knowledge_graph.graph import KnowledgeGraph
from core.knowledge_graph.identifiers import NodeId

@dataclass(frozen=True)
class GraphSnapshot:
    graph_id: str
    revision: int
    payload: str

class GraphRepository(Protocol):
    def save(self, graph_id: str, graph: KnowledgeGraph) -> KnowledgeGraph: ...
    def get(self, graph_id: str) -> KnowledgeGraph | None: ...
    def delete(self, graph_id: str) -> KnowledgeGraph: ...
    def exists(self, graph_id: str) -> bool: ...
    def list_ids(self) -> list[str]: ...
    def snapshot(self, graph_id: str) -> GraphSnapshot: ...
    def restore(self, snapshot: GraphSnapshot) -> KnowledgeGraph: ...
    def find_node(self, graph_id: str, node_id: NodeId): ...
